### ISSUE TITLE
[Feature] User And Admin Panel

### ISSUE THREAD

**Issue by arnon001** [PapaSnags/Discord-BOT-Dashboard#7]
Hey!,
Can You Do A User Panel That (for Any Server) So The Server Owner Can Choose Which Command They Wanna Disable And The Admin Panel (For The Owners) So They Can Change The Bot Status Make Him Offline And More Perks,
If You Want More Explain Add Me: Arnon001#7584
Or Send a mail: arnonhacohen123@gmail.com

**Comment by LachlanDev** [comment]
Hey,
Thanks for the idea @arnonGPMC I am currently working a resign for Discord BOT Dashboard, if you want to see some more features feel free to send them here.
Thanks!
